Add CTO & COO to the Website
datavisyn/datavisyn.github.io pull request #61
Opened 2019-10-16 08:17 UTC by dvvanessastoiber

Dominic and Anita are added to the Website. Furthermore, all links to social media profiles etc. are now opened in a new tab and the datavisyn linkedin profile is added to the social buttons in the footer.

2019-10-16 08:22 UTC, dvvanessastoiber commented
Anita and Dominic are added to the Website:

![image](https://user-images.githubusercontent.com/52395160/66901382-e2f5c500-effe-11e9-8c34-d6080117adda.png)

2019-10-16 08:29 UTC, mstreit commented
Looks good. The heading should be changed from 'Founders' to 'Founders and Management'. And maybe a 3x2 layout looks better?

2019-10-16 08:31 UTC, mstreit commented
And maybe we should use the full job title instead of the abbreviations? (Chief Technology Officer instead of CTO, etc.).

2019-10-16 09:14 UTC, dvvanessastoiber commented
Is it okay like that?

![image](https://user-images.githubusercontent.com/52395160/66905363-040de400-f006-11e9-8de1-42fdd94c31d8.png)

2019-10-16 09:33 UTC, mstreit commented
Perfect, thanks! Please also check if it looks okay on mobile devices and different resolutions/window sizes.

2019-10-16 10:51 UTC, lehnerchristian commented
here are some more screenshots

the smartphone version:
![website_smartphone](https://user-images.githubusercontent.com/1711080/66912546-0f1b4100-f013-11e9-986b-157df7589fa4.png)

the tablet version (ipad in this case):
![website_ipad_3x2](https://user-images.githubusercontent.com/1711080/66912600-2f4b0000-f013-11e9-98b8-8f7ca257feb4.png)


the tablet version looks probably a bit crowded with a 3x2 grid (this was already a problem before). alternatively we could use a 2x3 grid:
![website_ipad_2x3](https://user-images.githubusercontent.com/1711080/66912699-5acdea80-f013-11e9-8685-f018e77acda3.png)

2019-10-16 10:52 UTC, lehnerchristian commented
and the header is now `Founders and Management` --> should we update the link in the navigation?

2019-10-16 10:58 UTC, mstreit commented
The term 'Team' is probably better suited for the top menu. Thanks!

2019-10-16 13:39 UTC, lehnerchristian requested changes

2019-10-16 13:39 UTC, lehnerchristian commented on _sass/team.scss
> +    width: 35%;
```suggestion
    width: 50%;
```

let's use 50%, because marc's long subtitle will break lines multiple times

2019-10-17 06:30 UTC, lehnerchristian approved these changes

2019-10-17 06:31 UTC, merged